import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { toast, Toaster } from "sonner";
import { initValues } from "@/actions/query-actions";
import {NextUIProvider} from '@nextui-org/react';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const initQuery: any = await initValues();
  if (initQuery.error) {
    toast.error(initQuery.error);
  }

  return (
    <html lang="en">
      <body className={inter.className}>
      <NextUIProvider>
        {children}
        </NextUIProvider>
      <Toaster richColors expand={true}  />
      </body>

    </html>
  );
}
